<div class="col-md-9 col-sm-12 mar-top-30">
    <div class="row">
        <div class="col-sm-12 ">

            <!-- thông tin tài khoản -->
            <div class="bd-bt">
                <div class="card1 mb-3">
                    <div class="row no-gutters">
                        <div class="col-2">
                            <!-- tải ảnh đại diện -->
                            <?php
                    include ('upload-avatar.php');
                ?>
                        </div>
                        <div class="col-10">
                            <div class="card-body avt-bd">
                                <span class="card-text">
                                    Tên tài khoản: <strong class="info-cl">
                                        <?php echo $_SESSION["user_name"] ?>></strong>
                                </span>
                                <div> Mật khẩu: <strong> ********</strong>
                                    <!-- Đổi mật khẩu -->
                                    <?php
                            include ('change-pass.php');
                        ?>
                                </div>
                                <p> Ngày tạo: <strong class="info-cl"> 20/11/2019</strong></p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <!-- thông tin cá nhân -->
            <div class="mg-t-l-15">
                <div class="container">
                    <!-- Trigger the modal with a button -->
                    <a href="" class="right info-cl font-size-12" data-toggle="modal" data-target="#myModal12">Thay
                        đổi</a>
                    <div id="myModal12" class="modal fade" role="dialog">
                        <div class="modal-dialog">
                            <!-- Modal content-->
                            <div class="modal-content">
                                <div class="md-hd-cl">
                                    <h5>Thay đổi thông tin cá nhân</h5>
                                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                                </div>
                                <div class="modal-body">
                                    <!-- <p>Nội dung của Modal.</p> -->
                                    <form class="container">
                                        <div class="form-group">
                                            <label for="formGroupExampleInput">Họ và tên:</label>
                                            <input type="text" class="form-control" id="formGroupExampleInput"
                                                placeholder="....">
                                        </div>
                                        <div class="form-group">
                                            <label for="formGroupExampleInput2">Giới tính:</label>
                                            <input type="text" class="form-control" id="formGroupExampleInput2"
                                                placeholder="...">
                                        </div>
                                        <div class="form-group">
                                            <label for="formGroupExampleInput2">Ngày sinh:</label>
                                            <input type="text" class="form-control" id="formGroupExampleInput2"
                                                placeholder=".....">
                                        </div>
                                        <div class="form-group">
                                            <label for="formGroupExampleInput2">Địa chỉ</label>
                                            <input type="text" class="form-control" id="formGroupExampleInput2"
                                                placeholder="....">
                                        </div>
                                        <div class="form-group">
                                            <label for="formGroupExampleInput2">Email</label>
                                            <input type="text" class="form-control" id="formGroupExampleInput2"
                                                placeholder="......">
                                        </div>
                                        <a href="profile.php"><button type="button" class="btn btn-info right">
                                                Xác nhận
                                            </button></a>
                                        <button type="reset" class="btn btn-info left"> Nhập lại</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <h4 class="info-cl mg-bt-15">Thông tin cá nhân</h4>
                <div class="mg-l-30">
                    <small> Họ và tên:</small>
                    <span class="card-text"><strong> Phan Mạnh Dũng</strong> </span> <br>
                    <small> Giới tính:</small>
                    <span class="card-text"><strong> Nam</strong></span> <br>
                    <small> Ngày sinh:</small>
                    <span class="card-text"><strong> 21/12/1995</strong></span> <br>
                    <small> Địa chỉ:</small>
                    <span class="card-text"><strong> a</strong></span> <br>
                    <small> Số điện thoại:</small>
                    <span class="card-text"><strong> 0123456789</strong></span> <br>
                    <small> Địa chỉ email:</small>
                    <span class="card-text"><strong> DCD_dick@abc.com</strong></span> <br>
                </div>
            </div>
        </div>
    </div>
</div>