<main id="main" class="site-main">
    <div class="container">
        <div class="row">
            <div class="holder">
                <div class="album ">
                    <div class="heart"><i class="fas fa-heart"></i></div>
                    <img src="<?php echo BASE_URL ;?>public/images/<?php echo $data["id_song"]["song_img"]?>" alt="pic" width="220px" height="220px">
                </div>
                <div class="currently-playing">
                    <h2 class="song-name1"><?php echo $data["id_song"]["song_name"]?></h2>
                    <h3 class="artist-name"><?php echo $data["id_song"]["singer_name"]?></h3>
                    <h4 class="artist-name">Album: <?php echo $data["id_song"]["album_name"]?></h4>

                </div>
                <div class="audio green-audio-player">
                    <div class="loading">
                        <div class="spinner"></div>
                    </div>
                    <div class="play-pause-btn">
                        <svg xmlns="http://www.w3.org/2000/svg" width="18" height="24" viewBox="0 0 18 24">
                            <path fill="#566574" fill-rule="evenodd" d="M18 12L0 24V0" class="play-pause-icon"
                                id="playPause" />
                        </svg>
                    </div>

                    <div class="controls">
                        <span class="current-time">0:00</span>
                        <div class="slider" data-direction="horizontal">
                            <div class="progress">
                                <div class="pin" id="progress-pin" data-method="rewind"></div>
                            </div>
                        </div>
                        <span class="total-time">0:00</span>
                    </div>

                    <div class="volume">
                        <div class="volume-btn">
                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
                                <path fill="#566574" fill-rule="evenodd"
                                    d="M14.667 0v2.747c3.853 1.146 6.666 4.72 6.666 8.946 0 4.227-2.813 7.787-6.666 8.934v2.76C20 22.173 24 17.4 24 11.693 24 5.987 20 1.213 14.667 0zM18 11.693c0-2.36-1.333-4.386-3.333-5.373v10.707c2-.947 3.333-2.987 3.333-5.334zm-18-4v8h5.333L12 22.36V1.027L5.333 7.693H0z"
                                    id="speaker" />
                            </svg>
                        </div>
                        <div class="volume-controls hidden">
                            <div class="slider" data-direction="vertical">
                                <div class="progress">
                                    <div class="pin" id="volume-pin" data-method="changeVolume"></div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <audio crossorigin>
                        <source src="<?php echo BASE_URL ;?>/public/songs/<?php echo $data["id_song"]["link_song"]?>"
                            type="audio/mpeg">
                    </audio>
                </div>
            </div>
        </div>
        <div class="row mb-10">
            <div class="col-xl-12 col-lg-12col-sm-12">
                <div class="views">
                    <div class="view-item upload-infor">
                        <div class="upload-infor-item">
                            <span>Upload:</span>
                        </div >
                        <div class="upload-infor-item">
                        <p>
                        <?php if ($data["id_song"]["status_song"] == '1') {
                            # code...
                         echo $data["id_song"]["user_name"];
                        }else {
                            echo "Chờ Phê Duyệt" ;
                        }?>
                        </p>
                        </div>
                    </div>
                    <div class="view-item">

                    </div>
                    <div class="view-item">

                    </div>
                    <div class="view-item">

                    </div>
                    <div class="view-item">

                    </div>
                    <div class="view-item">

                    </div>
                    <div class="view-item">

                    </div>
                    <div class="view-item">

                    </div>
                    <div class="view-item countViews">
                        <img src="<?php echo BASE_URL;?>public/images/icon/play-button.png" alt="icon" width="15px"
                            height="15px">
                        <span><?php echo $data["id_song"]["views"]; ?></span>
                    </div>

                </div>
            </div>

        </div>
        <div class="row mb-40">
            <!-- Lời bài hát -->
            <div class="col-xl-8 col-lg-8 col-sm-12">
                <div class="">
                    <img src="<?php echo BASE_URL;?>public/images/icon/note.png" alt="icon" width="20px" height="20px">
                    <h3>Lời Bài Hát</h3>
                </div>
                <div class="lysic">
                    
                    <?php if (isset($data["id_song"]["liycs_song"])) {?>
                        <pre>
                            <?php echo $data["id_song"]["liycs_song"]; ?>
                        </pre>
                        
                  <?php  } 
                    else {?>
                      <span>Lời bài hát chưa được cập nhật</span>
                   <?php  }?>
               
                
                </div>
            </div>
            <!-- Bảng xếp hạng -->
            <div class="col-xl-4 col-lg-4 col-sm-12 top">
                <h3><?php echo "BXH ".mb_strtoupper($data["id_song"]["region_name"]);?></h3>
                <ul class="ranking">
                    <?php $count=1?>
                    <?php  while($row=mysqli_fetch_array($data["topregion"])){?>
                    <li>

                        <a href="<?php echo BASE_URL ;?>/Song/Listenit/<?php echo $row["id_song"]?>">
                            <div class="song">
                                <?php switch ($count) {
                                case '1':?>
                                <div class="song-item song-rank" style="color:#4a90e2;">
                                    <?php echo "0".$count;?>
                                </div>
                                <?php  break; 
                                 case '2':?>
                                <div class="song-item song-rank" style="color:#50e3c2;">
                                    <?php echo "0".$count;?>
                                </div>
                                <?php    break; 
                                      case '3':?>
                                <div class="song-item song-rank" style="color:red;">
                                    <?php echo "0".$count;?>
                                </div>
                                <?php  break; 
                                default:?>
                                <div class="song-item song-rank" style="color:#333;">
                                    <?php echo "0".$count;?>
                                </div>
                                <?php  break;
                            } ?>
                                <div class="song-item song-image">
                                    <img src="<?php echo BASE_URL ;?>/public/images/<?php echo $row["song_img"]?>"
                                        alt="#">
                                </div>
                                <div class="song-item song-info1">
                                    <p class="song-name">
                                        <?php echo mb_strtoupper($row["song_name"]); ?>
                                    </p>
                                    <p class="singer">

                                        <?php echo $row["singer_name"]; 
                           
                        ?>
                                    </p>
                                </div>
                            </div>
                        </a>
                    </li>
                    <?php $count++;}?>
                </ul>
            </div>


        </div>
        <h3>Có Thể Bạn Quan Tâm</h3>
        <div class="row mb-40 ">
            <?php  while($row=mysqli_fetch_array($data["datasong"])){?>
            <div class="col-xl-4 col-lg-4 col-sm-6">
                <ul class="ranking">
                    <li>
                        <a href="<?php echo BASE_URL ;?>/Song/Listenit/<?php echo $row["id_song"]?>">
                            <div class="song">
                                <div class="song-item song-image">
                                    <img src="<?php echo BASE_URL ;?>/public/images/<?php echo $row["song_img"]?>"
                                        alt="#">
                                </div>
                                <div class="song-item song-info1">
                                    <p class="song-name">
                                        <?php echo mb_strtoupper($row["song_name"]); ?>
                                    </p>
                                    <p class="singer">

                                        <?php echo $row["singer_name"]; ?>
                                    </p>
                                </div>
                            </div>
                        </a>
                    </li>

                </ul>
            </div>
            <?php }?>
        </div>
    </div>
</main>