
    <div id="myModal" class="modal fade" role="dialog">
        <div class="modal-dialog">
            <!-- Modal content-->
            <div class="modal-content">
                <div class="center-container bgr-img">
                    <!--header-->
                    <a class="removeimg" href="javascript:">
                        <div class="topright removeimg">
                            <button type="button" class="close close1" data-dismiss="modal">&times;</button>
                        </div>
                    </a>
                    <div class="header-w3l">
                        <h1>The Word Of music</h1>
                    </div>
                    <!--//header-->
                    <div class="main-content-agile">
                        <div class="sub-main-w3 a1">
                            <div class="wthree-pro">
                                <h2>Login Quick</h2>
                            </div>
                            <form action="#" method="post">
                                <div class="pom-agile">
                                    <input placeholder="User name" name="Name" class="user" type="text" required="">
                                    <span class="icon1"><i class="fa fa-user" aria-hidden="true"></i></span>
                                </div>
                                <div class="pom-agile">
                                    <input placeholder="Password" name="Password" class="pass" type="password"
                                        required="">
                                    <span class="icon2"><i class="fa fa-unlock" aria-hidden="true"></i></span>
                                </div>

                                <div class="sub-w3l">
                                    <h6>
                                        <div class="gird">
                                        <a  href="" data-toggle="modal" data-target="#myModal1"
                                                class="left pd-l-25">Register</a>
                                           
                                            <a href="#" class="right pd-r-25">Forgot Password?</a>
                                        </div>

                                    </h6>
                                    <div class="right-w3l">
                                        <input type="submit" value="Login">
                                    </div> 
                                </div>
                            </form>
                        </div>
                    </div>
                    <!--//main-->
                </div>
            </div>
        </div>
    </div>