<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Trang Quản Trị DCD Music</title>
    <link rel="shortcut icon" href="<?php echo BASE_URL ;?>/public/images/logo/logobar.png" type="image/png">
    <link rel="stylesheet" href="<?php echo BASE_URL ;?>public/css/admin2.css" media="all">
    <link rel="stylesheet" href="<?php echo BASE_URL ;?>public/css/main.css" media="all">
    <link rel="stylesheet" href="<?php echo BASE_URL ;?>public/css/style.css" media="all">

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous">
    </script>




    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous">
    </script>
</head>

<body class="a-cl">
    <nav class="navbar sticky-top navbar-ligh">
        <!-- LOGO -->
        <div class="logo">
            <div>
                <img src="<?php echo BASE_URL ;?>public/images/icon/menu.png" id="sidebarCollapse" alt=""
                    class="sidebar left mar-top-15">
            </div>

            <div class="logo-wrapper">
                <a href="<?php echo BASE_URL ;?>"><img src="<?php echo BASE_URL ;?>public/images/logo/logo-web.png"
                        alt="logo" width="90%"></a>
            </div>

        </div>
      

     

        <div class="dropdown">
            <button class="btn dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown"
                aria-haspopup="true" aria-expanded="false" class="avatar">
                <?php if (isset($_SESSION["user_img"])) {?>

                <img src="<?php echo BASE_URL ;?>public/images/avatar/<?php echo $_SESSION["user_img"]?>" alt=""
                    width="40px" height="40px">
                <?php  }
              else {?>
                <img class="avatar" src="<?php echo BASE_URL ;?>public/images/icon/user.png" alt="" width="40px"
                    height="40px">
                <?php  }?>

            </button>
            <div class="dropdown-menu abc" aria-labelledby="dropdownMenuButton">
                <a class="dropdown-item" href="<?php echo BASE_URL ;?>">Đi đến Site</a>
                <a class="dropdown-item" href="#">Đổi Mật Khẩu</a>
                <a class="dropdown-item" href="#">Đăng Xuất</a>
            </div>
        </div>
    </nav>

    <div class="ad-flex">
        <div class="gird">
            <div class="wrapper">
                <!-- Sidebar -->
                <nav id="sidebar">
                    <div class="sidebar-header">
                        <div class="hearder-item">
                            <?php if (isset($_SESSION["user_img"])) {?>

                            <img class="avatar"
                                src="<?php echo BASE_URL ;?>public/images/avatar/<?php echo $_SESSION["user_img"]?>"
                                alt="" width="70px" height="70px">
                            <?php  }
                            else {?>
                            <img src="<?php echo BASE_URL ;?>public/images/icon/user.png" alt="" class="avatar"
                                width="70px" height="70px">
                            <?php  }?>
                        </div>
                        <div class="hearder-item welcome ">
                            <div class="wel">Chào Mừng</div>
                            <div><?php echo  $_SESSION['user_fullname']?></div>
                        </div>

                    </div>

                    <ul class="list-unstyled components menu">

                        <!-- <li>
                            <a href="#"><img src="<?php echo BASE_URL ;?>public/images/icon/house (1).png" alt="">
                                Trang Chủ</a>
                        </li> -->
                        <li>
                            <a href="<?php echo BASE_URL; ?>Admin/Show"> <img src="<?php echo BASE_URL ;?>public/images/icon/graph.png" alt="">
                                Thống Kê</a>
                        </li>
                        <li>
                            <a href="#pageSubmenu1" data-toggle="collapse" aria-expanded="false"
                                class="dropdown-toggle space"><img
                                    src="<?php echo BASE_URL ;?>public/images/icon/compact-disc.png" alt=""> Quản lý bài
                                hát</a>
                            <ul class="collapse list-unstyled active" id="pageSubmenu1">
                                <li>
                                    <a href="<?php echo BASE_URL; ?>ManageSong/Show">Bài Hát Trên Site</a>
                                </li>
                                <li>
                                    <a href="<?php echo BASE_URL; ?>Approval/Show">Chờ Xử Lý <span
                                            class="result1"><?php echo  $_SESSION["recors"];?></span></a>
                                </li>

                            </ul>
                        </li>
                        <?php if ($_SESSION['id_role']=='A') {?>
                        <li>
                            <a href="#pageSubmenu" data-toggle="collapse" aria-expanded="false"
                                class="dropdown-toggle space"><img
                                    src="<?php echo BASE_URL ;?>public/images/icon/users.png" alt="">Quản Lý Tài
                                Khoản</a>
                            <ul class="collapse list-unstyled" id="pageSubmenu">
                                <li>
                                    <a href="<?php echo BASE_URL; ?>Account/Show">Tài Khoản Người Dùng</a>
                                </li>
                                <li>
                                    <a href="<?php echo BASE_URL; ?>Account/admin">Tài Khoản Nhân Viên</a>
                                </li>

                                <li>
                                    <a href="<?php echo BASE_URL; ?>Account/singer">Tài Khoản Ca Sĩ</a>
                                </li>


                            </ul>
                        </li>
                        <?php  } ?>
                        <li>
                            <a href="<?php echo BASE_URL;?>Category" class=""><img src="" alt="">Thể loại</a>
                        </li>
                        <li>
                            <a href="<?php echo BASE_URL;?>Album/Show" class=""><img src="" alt="">Album</a>
                        </li>
                        <li>
                        <!-- <li>
                            <a href="#pageSubmenu2" data-toggle="collapse" aria-expanded="false"
                                class="dropdown-toggle space"><img
                                    src="<?php echo BASE_URL ;?>public/images/icon/news.png" alt="">Quản Lý Bảng Tin</a>
                            <ul class="collapse list-unstyled" id="pageSubmenu2">
                                <li>
                                    <a href="">Thêm Tin</a>
                                </li>
                                <li>
                                    <a href="">Danh Sách Tin</a>
                                </li>
                            </ul>
                        </li> -->
                        <!-- <li>
                            <a href="#pageSubmenu2" class=""><img
                                    src="<?php echo BASE_URL;?>public/images/news.png" alt=""> Themen
                                Song</a>
                        </li>
                        <li>
                            <a href="#pageSubmenu2" class=""><img
                                    src="<?php echo BASE_URL;?>public/images/news.png" alt=""> Fooder</a>
                        </li>
                        <li>
                            <a href="<?php echo BASE_URL;?>Account" class=""><img
                                    src="<?php echo BASE_URL;?>public/images/news.png" alt=""> Logo</a>
                        </li>

                        <li>
                            <a href=""> <img src="<?php echo BASE_URL ;?>public/images/icon/telemarketer.png" alt="">
                                Customer support</a>
                        </li> -->
                    </ul>
                </nav>
            </div>
        </div>
        <div class="body-ad">
            <!-- table -->
            <?php  include "./mvc/views/page/".$data['page'].".phtml";?>

        </div>
    </div>

    <footer id="footer" class="site-footer">
            <div class="container">
                <div class="contents">
                    <div class="contents-item">
                        <p>Copyright© 2019 - Bản quyền thuộc DCD Team </p>
                    </div>
                </div>

            </div>

        </footer>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous">
    </script>
    <!-- Popper.JS -->

    <script src="<?php echo BASE_URL; ?>ppublic/js/admin.js"></script>

    <script src="<?php echo BASE_URL ;?>public/js/mypage.js"></script>
    </script>
</body>

</html>