<!DOCTYPE HTML>
<html lang="en">

<head>
    <title>Register</title>
    <!-- Meta tag Keywords -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="keywords"
        content="Online Login Form Responsive Widget,Login form widgets, Sign up Web forms , Login signup Responsive web form,Flat Pricing table,Flat Drop downs,Registration Forms,News letter Forms,Elements" />
    <script type="application/x-javascript">
    addEventListener("load", function() {
        setTimeout(hideURLbar, 0);
    }, false);

    function hideURLbar() {
        window.scrollTo(0, 1);
    }
    </script>
    <!-- Meta tag Keywords -->
    <!-- css files -->
    <link rel="stylesheet" href="./public/css/loginRegister.css" type="text/css" media="all" /> <!-- Style-CSS -->
    <link rel="stylesheet" href="./public/css/font-awesome.css"> <!-- Font-Awesome-Icons-CSS -->

    <!-- //css files -->
</head>

<body>
    <!-- main -->
    <div class="center-container">
        <!--header-->
        <div class="header-w3l">
            <h1>The Word Of music</h1>
        </div>
        <!--//header-->
        <div class="main-content-agile">
            <div class="sub-main-w3 a1">
                <div class="wthree-pro">
                    <h2>Register Quick</h2>
                </div>
                <form action="<?php echo BASE_URL;?>Register/UserSingup" method="post">
                    <div class="pom-agile">
                        <input placeholder="User Name" name="name" class="user" type="text" required="">
                        <span class="icon1"><i class="fa fa-user" aria-hidden="true"></i></span>
                    </div>
                    <div class="pom-agile">
                        <input placeholder="Password" name="password" class="pass" type="password" required="">
                        <span class="icon2"><i class="fa fa-unlock" aria-hidden="true"></i></span>
                    </div>
                    <!-- <div class="pom-agile">
                        <input placeholder="Retype password" name="rePassword" class="pass" type="password" required="">
                        <span class="icon2"><i class="fa fa-unlock" aria-hidden="true"></i></span>
                    </div> -->
                    <div class="pom-agile">
                        <input placeholder="Email" name="email" class="pass" type="email" required="">
                        <span class="icon2"><i class="fa fa-mail-reply" aria-hidden="true"></i></span>
                    </div>
                    <div class="sub-w3l">
                        <h6>
                            <a href="<?php echo BASE_URL?>Home/Login" class="left">Login</a>
                        </h6>
                        <div class="right-w3l">
                            <input type="submit" value="Register" name="reg">
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <!--//main-->
    </div>
</body>

</html>